apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexvion
  labels:
    app: nexvion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexvion
  template:
    metadata:
      labels:
        app: nexvion
    spec:
      containers:
        - name: nexvion
          image: nexvion:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
